[package]
name = "zappy_server"
version = "0.1.0"
edition = "2024"

include = [
    "src/main.rs",
    "src/server/mod.rs",
    "src/server/server.rs",
    "src/server/config.rs",
    "src/server/scheduler.rs",
    "src/server/net/mod.rs",
    "src/server/net/connection.rs",
    "src/server/net/reactor.rs",
    "src/server/game/mod.rs",
    "src/server/game/command.rs",
    "src/server/game/gui.rs",
    "src/server/game/map.rs",
    "src/server/game/world.rs",
    "src/server/game/player.rs",
    "src/server/game/team.rs",
    "Cargo.toml",
]

[dependencies]
libc = "0.2"
