[package]
name = "zappy_server"
version = "0.1.0"
edition = "2024"

include = [
    "src/main.rs",
    "src/server/server.rs",
    "src/server/mod.rs",
    "src/server/config.rs",
    "src/server/map.rs",
    "src/server/client/client.rs",
    "src/server/client/mod.rs",
    "Cargo.toml",
]

[dependencies]
clap = { version = "4", features = ["derive"] }
