name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MIRROR_SSH: git@github.com:EpitechPGE2-2025/G-YEP-400-LIL-4-1-zappy-11.git
  EXECUTABLES: zappy_server,zappy_ai,zappy_gui
jobs:
  check_program_compilation:
    if: github.repository != 'EpitechPGE2-2025/G-YEP-400-LIL-4-1-zappy-11'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: fetching
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install raylib
        run: |
          apt-get install -y --no-install-recommends libgl-dev libx11-dev
          curl -L "https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_linux_amd64.tar.gz" -o /tmp/raylib.tar.gz
          tar -xzf /tmp/raylib.tar.gz -C /tmp/
          cp /tmp/raylib-5.0_linux_amd64/include/* /usr/local/include/
          cp /tmp/raylib-5.0_linux_amd64/lib/libraylib.a /usr/local/lib/
        shell: bash
      - name: make
        run: timeout 2m make
        shell: bash
      - name: check_executables
        run: |
          files=$(echo "$EXECUTABLES" | tr ',' ' ')
          for file in $files; do
            if [[ -e "$file" ]]; then
              echo "::notice::$file is here"
            else
              echo "::error::$file is missing"
              exit 1
            fi
          done
        shell: bash
      - name: make clean
        run: make clean
        shell: bash
  
  run_tests:
    if: github.repository != 'EpitechPGE2-2025/G-YEP-400-LIL-4-1-zappy-11'
    needs:
      - check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: fetching
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install python dependencies
        run: pip3 install pytest pytest-asyncio
        shell: bash
      - name: make tests_run
        run: timeout 2m make tests_run
        shell: bash

  push_to_mirror:
    if: ${{ github.repository != 'EpitechPGE2-2025/G-YEP-400-LIL-4-1-zappy-11' && github.event_name == 'push' }}
    needs:
      - check_program_compilation
      - run_tests
    runs-on: ubuntu-latest
    steps:
      - name: fetching
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_SSH }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
